# Generated by Django 5.2.9 on 2025-12-16 07:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оплаты')),
                ('payment_type', models.CharField(choices=[('subscription', 'Оплата абонемента'), ('training', 'Индивидуальная тренировка'), ('locker', 'Аренда шкафчика'), ('other', 'Прочее')], default='subscription', max_length=20, verbose_name='Тип платежа')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('transfer', 'Банковский перевод'), ('online', 'Онлайн оплата')], default='cash', max_length=20, verbose_name='Метод оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('completed', 'Оплачен'), ('cancelled', 'Отменен'), ('refunded', 'Возвращен')], default='completed', max_length=20, verbose_name='Статус')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Начало периода')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Окончание периода')),
                ('receipt', models.FileField(blank=True, null=True, upload_to=payments.models.payment_receipt_path, verbose_name='Чек/квитанция')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client', verbose_name='Клиент')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.membership', verbose_name='Абонемент')),
                ('membership_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.membershipplan', verbose_name='Тарифный план')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('subscription_expiry', 'Истечение абонемента'), ('payment_due', 'Напоминание об оплате'), ('birthday', 'День рождения'), ('visit', 'Напоминание о посещении'), ('other', 'Прочее')], default='subscription_expiry', max_length=30, verbose_name='Тип напоминания')),
                ('send_date', models.DateTimeField(verbose_name='Дата отправки')),
                ('send_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push-уведомление'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], default='email', max_length=20, verbose_name='Способ отправки')),
                ('send_status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус отправки')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='clients.client', verbose_name='Клиент')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='subscriptions.membership', verbose_name='Абонемент')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='payments.payment', verbose_name='Платеж')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['send_date'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client', 'payment_date'], name='payments_pa_client__26ea91_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['client', 'send_date'], name='payments_re_client__616081_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['send_status'], name='payments_re_send_st_95b80a_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['send_date'], name='payments_re_send_da_da51a7_idx'),
        ),
    ]
