# Generated by Django 5.2.9 on 2025-12-16 04:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "Месячный безлимит", "Разовое посещение"', max_length=100, unique=True, verbose_name='Название тарифа')),
                ('description', models.TextField(blank=True, help_text='Подробное описание тарифа', null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('period_value', models.IntegerField(default=30, help_text='Например: 30 дней, 12 месяцев, 1 год', verbose_name='Значение периода')),
                ('period_type', models.CharField(choices=[('days', 'Дни'), ('months', 'Месяцы'), ('year', 'Год')], default='days', max_length=10, verbose_name='Тип периода')),
                ('visit_limit', models.IntegerField(blank=True, help_text='Оставьте пустым для безлимитного тарифа', null=True, verbose_name='Лимит посещений')),
                ('access_time', models.CharField(choices=[('any', 'Любое время'), ('day', 'Дневное (6:00-18:00)'), ('night', 'Ночное (18:00-6:00)'), ('weekend', 'Только выходные')], default='any', max_length=20, verbose_name='Время доступа')),
                ('can_freeze', models.BooleanField(default=False, help_text='Разрешить клиенту замораживать абонемент', verbose_name='Можно заморозить')),
                ('max_freeze_days', models.IntegerField(default=0, help_text='0 - без ограничений', verbose_name='Максимальная заморозка (дней)')),
                ('is_active', models.BooleanField(default=True, help_text='Отображается ли тариф для покупки', verbose_name='Активный тариф')),
                ('display_order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='subscriptio_is_acti_608f6f_idx'), models.Index(fields=['price'], name='subscriptio_price_512e72_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('remaining_visits', models.IntegerField(blank=True, null=True, verbose_name='Оставшиеся посещения')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('expired', 'Истек'), ('frozen', 'Заморожен'), ('cancelled', 'Отменен')], default='active', max_length=20, verbose_name='Статус')),
                ('auto_renewal', models.BooleanField(default=False, verbose_name='Автопродление')),
                ('frozen_until', models.DateField(blank=True, null=True, verbose_name='Заморожен до')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clients.client', verbose_name='Клиент')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='subscriptions.membershipplan', verbose_name='Тарифный план')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['client', 'status'], name='subscriptio_client__ccc914_idx'), models.Index(fields=['end_date'], name='subscriptio_end_dat_609a2d_idx'), models.Index(fields=['status'], name='subscriptio_status_dc3b78_idx')],
            },
        ),
    ]
